name: pylint
run-name: pylint
on: [push]
jobs:
  pylintjob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install python-docx pylint
      - run: python --version
      - run: pylint *.py
